version: '3.3'
services:
  backend:
    image: sunjido/234-project:latest
    ports:
      - "8086:8080"
  frontend:
    image: dto80/project234-frontend
    ports:
      - "8085:80"
    volumes:
      - type: bind
        source: ./Project234
        target: /usr/share/nginx/html/assets
